// import Image from "next/image";
// import Head from 'next/head';
// import ServiceCard from '@/components/ServiceCard';
// import SectionHeader from "@/components/SectionHeader";
// import Navbar from "@/components/Navbar";
import rectangle50 from '../../assets/Rectangle 50.png'
import group1 from '../../assets/Group (1).png'
// import rectangle52 from '../assets/Rectangle 52.png'
// import rectangle54 from '../assets/Rectangle 54.png'
// import rectangle60 from '../assets/Rectangle 60.png'
// import rectangle58 from '../assets/Rectangle 58.png'
// import rectangle56 from '../assets/Rectangle 56.png'
// import headerimage from '../assets/Rectangle 34624683.png'
import rectangle48 from '../../assets/Rectangle 48.png'
import Image from "next/image";
import HeroSection from "@/components/HeroSection";
import rectangle3 from '../../assets/Rectangle 3.png'
import image2 from '../../assets/image 2.png'
import youngbussiness from '../../assets/young-business-woman-student-teacher-tutor-wear-wireless-headset-video-conference-calling-laptop 1.png'
import Head from "next/head";
import ServiceCard from '@/components/ServiceCard';
import group93 from '../../assets/Group 93.png'
import rectangle52 from '../../assets/Rectangle 52.png'
import rectangle54 from '../../assets/Rectangle 54.png'
import rectangle60 from '../../assets/Rectangle 60.png'
import rectangle58 from '../../assets/Rectangle 58.png'
import rectangle56 from '../../assets/Rectangle 56.png'

const HomePage: React.FC = () => {



    const services = [
        {
            imageSrc: rectangle50,
            iconSrc: group1,
            title: "Document Translagfhfgtion",
            description:"Live interpretation is given by our staff of highly skilled, professional interpreters who provide dependable translation services for any of your LEP clients and is accessible to all through the Ria Lingo platform."
        },
        {
            imageSrc: rectangle52,
            iconSrc: group93,
            title: "Live Interpreting",
            description:"Live interpretation is given by our staff of highly skilled, professional interpreters who provide dependable translation services for any of your LEP clients and is accessible to all through the Ria Lingo platform."
       

        },
        {
            imageSrc: rectangle54,
            iconSrc: group93,
            title: "Video Remote Interpreting",
            description:"Live interpretation is given by our staff of highly skilled, professional interpreters who provide dependable translation services for any of your LEP clients and is accessible to all through the Ria Lingo platform."
       
        },
        {
            imageSrc: rectangle56,
            iconSrc: group93,
            title: "Transcription",
            description:"Live interpretation is given by our staff of highly skilled, professional interpreters who provide dependable translation services for any of your LEP clients and is accessible to all through the Ria Lingo platform."
       
        },
        {
            imageSrc: rectangle58,
            iconSrc: group93,
            title: "Voice-Overs",
            description:"Live interpretation is given by our staff of highly skilled, professional interpreters who provide dependable translation services for any of your LEP clients and is accessible to all through the Ria Lingo platform."
       
        },
        {
            imageSrc: rectangle60,
            iconSrc: group93,
            title: "Phone Interpreting",
            description:"Live interpretation is given by our staff of highly skilled, professional interpreters who provide dependable translation services for any of your LEP clients and is accessible to all through the Ria Lingo platform."
       
        }
    ];
    return (
        <>
            <Head>
                <title>Rainlingo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <HeroSection
                    title="Services"
                    imageSrc={image2}
                />

                <div className="w-full mt-10">
                    <div className="max-w-[90%] mx-auto">
                        <div className="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                            {services.map((service, index) => (
                                <ServiceCard
                                    key={index}
                                    imageSrc={service.imageSrc}
                                    iconSrc={service.iconSrc}
                                    title={service.title}
                                    description={service.description}
                                />
                            ))}
                        </div>
                    </div>
                </div>


            </main>

        </>
    );
};

export default HomePage;
