// import Image from "next/image";
// import Head from 'next/head';
// import ServiceCard from '@/components/ServiceCard';
// import SectionHeader from "@/components/SectionHeader";
// import Navbar from "@/components/Navbar";
// import rectangle50 from '../assets/Rectangle 50.png'
// import group1 from '../assets/Group (1).png'
// import rectangle52 from '../assets/Rectangle 52.png'
// import rectangle54 from '../assets/Rectangle 54.png'
// import rectangle60 from '../assets/Rectangle 60.png'
// import rectangle58 from '../assets/Rectangle 58.png'
// import rectangle56 from '../assets/Rectangle 56.png'
// import headerimage from '../assets/Rectangle 34624683.png'
import rectangle48 from '../../assets/Rectangle 48.png'
// import HeroSection from "@/components/HeroSection";
// import rectangle3 from '../assets/Rectangle 3.png'
// // "/assets/Rectangle 48.png"
// import Footer from "@/components/Footer";
import Image from "next/image";
import HeroSection from "@/components/HeroSection";
import rectangle3 from '../../assets/Rectangle 3.png'
import image2 from '../../assets/image 2.png'
import youngbussiness from '../../assets/young-business-woman-student-teacher-tutor-wear-wireless-headset-video-conference-calling-laptop 1.png'
import Head from "next/head";

const HomePage: React.FC = () => {

    return (
        <>
            <Head>
                <title>Rainlingo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <HeroSection
                    title="Interpreter"
                    imageSrc={image2}
                />


                <div className="mt-10">
                    <div className="max-w-[70%] mx-auto">
                        <p className="font-poppins font-semibold text-[#333333]  text-[14px] tracking-[0.14px] text-center ">
                            We're different and it shows in so many ways. RIA Lingo was designed to empower people, including the
                            amazing interpreters who use it. Interpreters matter to us and their work is the heart of our company!
                        </p>
                    </div>
                </div>


                <div className="w-full mt-10">
                    <div className="max-w-[80%] mx-auto">
                        <form>
                            {/* First Row */}
                            <div className="block md:flex md:gap-4">
                                {/* Left Column */}
                                <div className="w-full md:w-1/2">
                                    {[
                                        { label: "First Name", name: "firstName" },
                                        { label: "Last Name", name: "lastName" },
                                        { label: "Phone", name: "phone" },
                                        { label: "I want to become", name: "goal" },
                                    ].map((item, i) => (
                                        <div key={i} className="mb-5 w-full">
                                            <label
                                                htmlFor={item.name}
                                                className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                            >
                                                {item.label}
                                            </label>
                                            <input
                                                id={item.name}
                                                name={item.name}
                                                required
                                                className="shadow-xs bg-[#E7E7E7] border border-gray-300 text-gray-900 text-sm 
                      rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full 
                      p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 
                      dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light"
                                            />
                                        </div>
                                    ))}
                                </div>

                                {/* Right Column */}
                                <div className="w-full md:w-1/2">
                                    {[
                                        { label: "Interpretering Experience", name: "experience1" },
                                        { label: "Interpretering Experience", name: "experience2" },
                                        { label: "Password", name: "password", type: "password" },
                                        { label: "Industries", name: "industries" },
                                    ].map((item, i) => (
                                        <div key={i} className="mb-5">
                                            <label
                                                htmlFor={item.name}
                                                className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                            >
                                                {item.label}
                                            </label>
                                            <input
                                                id={item.name}
                                                name={item.name}
                                                type={item.type || "text"}
                                                required
                                                className="shadow-xs bg-[#E7E7E7] border border-gray-300 text-gray-900 text-sm 
                      rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full 
                      p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 
                      dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light"
                                            />
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Section Title */}
                            <div className="mb-5">
                                <p className="font-poppins text-[#401674] text-[20px] leading-[50px] tracking-normal">
                                    In these languages
                                </p>
                            </div>

                            {/* Language Experience */}
                            <div className="block md:flex md:gap-4">
                                {[1, 2].map((val) => (
                                    <div key={val} className="w-full md:w-1/2">
                                        <div className="mb-5">
                                            <label
                                                htmlFor={`languageExp${val}`}
                                                className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                            >
                                                Interpretering Experience
                                            </label>
                                            <input
                                                id={`languageExp${val}`}
                                                name={`languageExp${val}`}
                                                required
                                                className="shadow-xs bg-[#E7E7E7] border border-gray-300 text-gray-900 text-sm 
                      rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full 
                      p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 
                      dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light"
                                            />
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Multiple Inputs for Interpretering Experience */}
                            <div className="mb-5">
                                <label
                                    className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                >
                                    Interpretering Experience
                                </label>
                                <div className="flex-col space-y-4 md:flex md:gap-4">
                                    {[1, 2, 3].map((val) => (
                                        <input
                                            key={val}
                                            name={`expMulti${val}`}
                                            required
                                            className="shadow-xs bg-[#E7E7E7] border border-gray-300 text-gray-900 text-sm 
                    rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full 
                    p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 
                    dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light"
                                        />
                                    ))}
                                </div>
                            </div>

                            {/* Note Section */}
                            <div className="mb-5">
                                <label
                                    htmlFor="message"
                                    className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                >
                                    Note
                                </label>
                                <textarea
                                    id="message"
                                    name="note"
                                    rows={4}
                                    //   rows="4"
                                    className="block p-2.5 w-full text-sm bg-[#E7E7E7] rounded-lg border border-gray-300 
                focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 
                dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                />
                            </div>

                            {/* Submit Button */}
                            <div className="flex justify-center items-center">
                                <button
                                    type="submit"
                                    className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none 
                focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center 
                dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                                >
                                    Submit Now
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

            </main >

        </>
    );
};

export default HomePage;
