
import Image from "next/image";
import Head from 'next/head';
import ServiceCard from '@/components/ServiceCard';
import SectionHeader from "@/components/SectionHeader";
import Navbar from "@/components/Navbar";
import rectangle50 from '../assets/Rectangle 50.png'
import group1 from '../assets/Group (1).png'
import rectangle52 from '../assets/Rectangle 52.png'
import rectangle54 from '../assets/Rectangle 54.png'
import rectangle60 from '../assets/Rectangle 60.png'
import rectangle58 from '../assets/Rectangle 58.png'
import rectangle56 from '../assets/Rectangle 56.png'
import headerimage from '../assets/Rectangle 34624683.png'
import rectangle48 from '../assets/Rectangle 48.png'
import HeroSection from "@/components/HeroSection";
import clippath from '../assets/Clip path group.png'
import onlineremote from '../assets/online-remote-courses-high-view-student-her-desk 1.png';
import group145 from '../assets/Group 145.png';
import group70 from '../assets/Group 70.png'
import rectangle3 from '../assets/Rectangle 3.png'
import image2 from '../assets/image 2.png'
import Footer from "@/components/Footer";

const HomePage: React.FC = () => {

  const services = [
    {
      imageSrc: rectangle50,
      iconSrc: group1,
      title: "Document Translation"
    },
    {
      imageSrc: rectangle52,
      iconSrc: rectangle52,
      title: "Live Interpreting"
    },
    {
      imageSrc: rectangle54,
      iconSrc: rectangle54,
      title: "Video Remote Interpreting"
    },
    {
      imageSrc: rectangle56,
      iconSrc: rectangle54,
      title: "Transcription"
    },
    {
      imageSrc: rectangle58,
      iconSrc: rectangle54,
      title: "Voice-Overs"
    },
    {
      imageSrc: rectangle60,
      iconSrc: rectangle60,
      title: "Phone Interpreting"
    }
  ];

  return (
    <>
      <Head>
        <title>Rainlingo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <section className="w-full mt-8 bg-gradient-to-l from-transparent via-secondary to-primary py-10">
          <div className="max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 items-center px-6">
            <div className="text-white">
              <p className="text-lg leading-relaxed">
                Ria Lingo aims to provide expert interpretation and language service to the clients through the professional staff.
                We offer an integrated language platform that combines technology advancements with the need to deliver localized content.
              </p>
            </div>
            <div>
              <Image
                src={image2}
                alt="Home us"
                width={600}
                height={300}
                className="w-full h-[300px] object-cover rounded-xl shadow-md"
              />
            </div>
          </div>
        </section>

        <section className="w-full mt-12 mb-24">
          <div className="max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 px-6 items-center">
            <div>
              <Image
                src={rectangle48}
                alt="About us"
                width={600}
                height={300}
                className="w-full h-[300px] object-cover rounded-xl"
              />
            </div>
            <div>
              <h2 className="text-primary font-bold text-xl mb-2">About Us</h2>
              <p className="text-textPrimary font-semibold text-lg mb-2">
                Ria Lingo Professional Translate & Interpreting in just a few clicks
              </p>
              <p className="text-textSecondary text-sm">
                Ria Lingo was formed to serve Americans with expert language and translation services. We work closely with companies across all industry sectors, providing document translation, transcription, voice-overs, live interpreting, and video remote interpreting services.
              </p>
            </div>
          </div>
        </section>

        <SectionHeader subtitle="What We Do" title="Enjoy All The Services We Offer" />

        <section className="w-full mt-10">
          <div className="max-w-screen-xl mx-auto grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 px-6">
            {services.map((service, index) => (
              <ServiceCard
                key={index}
                imageSrc={service.imageSrc}
                iconSrc={service.iconSrc}
                title={service.title}
              />
            ))}
          </div>
        </section>

        <section className= "w-full mt-10 h-[400px] bg-gradient-to-l to-[#401674] via-[#A32CCA] from-[rgba(64,22,116,0)]">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 h-full px-6 items-center">
            <div className="text-white">
              <p className="text-lg leading-relaxed">
                Ria Lingo aims to provide expert interpretation and language service to the clients through the professional staff. We offer an integrated language platform that combines technology advancements with the need to deliver localized content.
              </p>
            </div>
            <div className="relative w-full h-[400px]">
               <Image
                src={onlineremote}
                alt="Online Remote Courses"
                fill
                className="object-cover"
              />
            </div>
          </div>
        </section>






        <section className="w-full bg-light py-16">
          <div className="max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 px-6">
            <div>
              <Image
                src={group145}
                alt="App Illustration"
                width={400}
                height={400}
                className="mx-auto object-cover"
              />
            </div>
            <div className="flex items-center">
              <div>
                <h2 className="text-primary font-bold text-4xl leading-tight mb-4">Download App</h2>
                <p className="text-textPrimary text-lg mb-4">Downloads our app and translate Everything</p>
                <div className="flex gap-4">
                  <Image src={clippath} alt="Google Play" width={100} height={50} />
                  <Image src={group70} alt="App Store" width={100} height={50} />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="w-full bg-dark py-12">
          <div className="max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 px-6 items-center">
            <div className="text-white">
              <h3 className="text-xl font-semibold mb-2">Become a Ria Lingo Interpreter.</h3>
              <p className="text-lg">
                Across the world, your language skills enable the conquering of language barriers.
              </p>
            </div>
            <div className="flex justify-center md:justify-end">
              <button className="py-2.5 px-10 text-sm font-medium text-white border-2 border-gray-400 rounded-full hover:bg-white hover:text-primary transition">
                Apply
              </button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default HomePage;


