// import Image from "next/image";
// import Head from 'next/head';
// import ServiceCard from '@/components/ServiceCard';
// import SectionHeader from "@/components/SectionHeader";
// import Navbar from "@/components/Navbar";
// import rectangle50 from '../assets/Rectangle 50.png'
// import group1 from '../assets/Group (1).png'
// import rectangle52 from '../assets/Rectangle 52.png'
// import rectangle54 from '../assets/Rectangle 54.png'
// import rectangle60 from '../assets/Rectangle 60.png'
// import rectangle58 from '../assets/Rectangle 58.png'
// import rectangle56 from '../assets/Rectangle 56.png'
// import headerimage from '../assets/Rectangle 34624683.png'
import rectangle48 from '../../assets/Rectangle 48.png'
import Image from "next/image";
import HeroSection from "@/components/HeroSection";
import rectangle3 from '../../assets/Rectangle 3.png'
import image2 from '../../assets/image 2.png'
import youngbussiness from '../../assets/young-business-woman-student-teacher-tutor-wear-wireless-headset-video-conference-calling-laptop 1.png'
import Head from "next/head";
import CoreValuesCard from '@/components/CoreValuesCard';
import group93 from '../../assets/Group 93.png'
const HomePage: React.FC = () => {


    const CoreValuesCardData = [
        {
            imageSrc: group93,
            title: "Carpentry Work/Flooring",
            description: "From installation maintenance to villa upkeep, we provide a spectrum of services to enhance your home's functionality and aesthetics."
        },
        {
            imageSrc: group93,
            title: "Carpentry Work/Flooring",
            description: "From installation maintenance to villa upkeep, we provide a spectrum of services to enhance your home's functionality and aesthetics."
        },
        {
            imageSrc: group93,
            title: "Carpentry Work/Flooring",
            description: "From installation maintenance to villa upkeep, we provide a spectrum of services to enhance your home's functionality and aesthetics."
        },
        {
            imageSrc: group93,
            title: "Carpentry Work/Flooring",
            description: "From installation maintenance to villa upkeep, we provide a spectrum of services to enhance your home's functionality and aesthetics."
        },
        {
            imageSrc: group93,
            title: "Carpentry Work/Flooring",
            description: "From installation maintenance to villa upkeep, we provide a spectrum of services to enhance your home's functionality and aesthetics."
        },
    ];




    return (
        <>
            <Head>
                <title>Rainlingo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <HeroSection
                    title="About Us"
                    imageSrc={image2}
                />

                <div className="w-full mt-[30px] mb-[100px]">
                    <div className="max-w-[85%] mx-auto">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10">
                            <div>
                                <Image
                                    src={rectangle48}
                                    alt="Service icon"
                                    width={0}
                                    height={0}
                                    sizes="100vw"
                                    className="w-full h-[300px] object-cover"
                                />

                            </div>
                            <div className="mt-20 lg:mt-0">
                                <div>
                                    <p className="text-neutral-800 font-bold text-lg leading-[50px] tracking-normal">
                                        About Us
                                    </p>
                                    <p className="font-poppins text-neutral-500 font-bold text-lg leading-[50px] tracking-normal">
                                        Ria Lingo Professional Translate & Interpreting in a just few clicks
                                    </p>
                                    <p className="font-poppins font-normal text-sm leading-[20px] tracking-normal text-[#424242]">
                                        Ria Lingo was formed to serve Americans with expert language and translation services.
                                        We work closely with companies across all industry sectors, providing document translation,
                                        transcription, voice-overs, live interpreting, and video remote interpreting services. By
                                        supporting quality-driven services and best practices, Ria Lingo establishes standards of
                                        excellence for translation services. Our team includes professionals who understand the
                                        importance of flawless language translation for your company's branding and credibility.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div className="w-full mt-[30px] mb-[100px]">
                    <div className="max-w-[85%] mx-auto">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10">
                            <div>
                                <div className="mt-20 lg:mt-0">
                                    <div>
                                        <p className="font-poppins text-[#353535] font-bold text-lg leading-[50px] tracking-normal">
                                            Mission
                                        </p>
                                        <p className="font-poppins font-normal text-sm leading-[20px] tracking-normal text-[#060606]">
                                            Ria Lingo aims to provide expert interpretation and language service to the clients
                                            through the professional staff. We offer an integrated language platform that combines
                                            technology advancements with the need to deliver localized content.
                                        </p>

                                        <p className="font-poppins text-[#353535] font-bold text-lg leading-[50px] tracking-normal">
                                            Vision
                                        </p>
                                        <p className="font-poppins font-normal text-sm leading-[20px] tracking-normal text-[#060606]">
                                            Ria Lingo envisions being a part of the leading translation services group by helping
                                            clients achieve their full potential.
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div className="mt-20 lg:mt-0 w-full h-[300px] relative">
                                <Image
                                    src={youngbussiness}
                                    alt="Business woman video conferencing"
                                    fill
                                    className="object-cover w-full"
                                    sizes="100vw"
                                    priority={false}
                                />
                            </div>
                        </div>
                    </div>
                </div>

                {/* <div className="mx-auto max-w-[70%] mt-[30px] ">
                    <p className="font-poppins text-[#401674]
                      text-[40px] mb-5 leading-[50px] font-semibold tracking-normal text-center">
                        Core Values
                    </p>

                    {CoreValuesCardData.map((cval, index) => (
                        <div className="flex ">
                            <CoreValuesCard
                                key={index}
                                index={index}
                                imageSrc={cval.imageSrc}
                                title={cval.title}
                                description={cval.description}
                            />
                        </div>
                    ))}

                </div> */}

            </main>

        </>
    );
};

export default HomePage;
